branches:
  only:
  - gh-pages
script: bundle exec jekyll build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: gh-pages
  target-branch: master
